services:
  beat-analyzer:
    build: .
    container_name: beat-analyzer
    user: "1027:100"
    environment:
      PUID: "1027"
      PGID: "100"
      TZ: Asia/Riyadh
      UMASK: "022"
    volumes:
      - /volume1/docker/containers/beat-analyzer:/data
      - /volume1/data/media/beat-analyzer:/import
    ports:
      - "8000:8000/tcp"
    network_mode: synobridge
    security_opt:
      - no-new-privileges:true
    restart: always
